### ISSUE TITLE
看着很不错，希望作者可以一直更新

### ISSUE THREAD

**Issue by tianshaokai** [lizixian18/NiceMusic#2]
1. 希望加一个入口打开正在播放的歌曲
2. 再一个是歌词查看全部歌词，和边播放和播放进度加载效果

**Comment by lizixian18** [comment]
谢谢你的建议，我会考虑进去的，因为现在还算是为了测试MusicLibrary而做的一个播放器，所以功能比较简单，也比较粗糙，之后会慢慢完善的，现在的数据接口不太好，如果有发现较好的接口也欢迎告诉我。^_^
