### ISSUE TITLE
使用了你的musiclibrary到项目中有一个问题！

### ISSUE THREAD

**Issue by jinhuizxc** [lizixian18/NiceMusic#3]
引入到项目中后打开音乐播放界面，音乐可以播放，暂停音乐后返回再次打开音乐播放界面发现声音播放，但是进度条没有移动，请问这个bug怎么解决？

**Comment by lizixian18** [comment]
要调用 TimerTaskManager#scheduleSeekBarUpdate()方法才会开始获取进度

**Comment by jinhuizxc** [comment]
加你qq，我们可以交流下，这里不方便，我的qq：1004260403
