### ISSUE TITLE
锁屏页面

### ISSUE THREAD

**Issue by hyandroid** [lizixian18/NiceMusic#4]
问一下，锁屏播放页面的处理逻辑在哪？

**Comment by hyandroid** [comment]
麻烦老哥解答一下，，找了半天找不到

**Comment by lizixian18** [comment]
MediaSessionManager

**Comment by hyandroid** [comment]
哦。是哪个Activity呢，

**Comment by hyandroid** [comment]
就是页面布局在哪。。

**Comment by hyandroid** [comment]
就是那个页面布局在哪。。

**Comment by lizixian18** [comment]
没有布局，没有activity，锁屏的界面是系统的

**Comment by hyandroid** [comment]
好的。谢谢

**Comment by lizixian18** [comment]
不止是 MediaSessionManager ，里面的参数是在其他类封装好回调进去的，你可以搜索一下 MediaSessionManager 在哪些地方用到，就能找出来了。

**Comment by lizixian18** [comment]
有问题可以加我qq细说

**Comment by hyandroid** [comment]
嗯，好，锁屏页面具体是怎么触发被调出来的， 是有锁屏监听吗

**Comment by hyandroid** [comment]
好啊，你QQ多少，970360505
